# Generated by Django 4.1.5 on 2023-01-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0003_event_prizes")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="Decription",
            field=models.TextField(max_length=500),
        )
    ]
