# Generated by Django 4.1.5 on 2023-01-07 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0007_rating")]

    operations = [
        migrations.RenameField(model_name="event", old_name="author", new_name="host")
    ]
